export { default as ArrowIcon } from './new/ArrowIcon';
export { default as CheckIcon } from './new/CheckIcon';
export { default as QuestionIcon } from './new/QuestionIcon';
export { default as EyeIcon } from './new/EyeIcon';
export { default as InfoIcon } from './new/InfoIcon';
export { default as CalendarIcon } from './new/CalendarIcon';
export { default as CloseCircleIcon } from './new/CloseCircleIcon';
export { default as CloseIcon } from './new/CloseIcon';
export { default as CreditCardIcon } from './new/CreditCardIcon';
export { default as MicIcon } from './new/MicIcon';
export { default as PointArrowIcon } from './new/PointArrowIcon';
export { default as ProfileCircleIcon } from './new/ProfileCircleIcon';
export { default as ProfileIcon } from './new/ProfileIcon';
export { default as CountIcon } from './new/CountIcon';
export { default as LoadIcon } from './new/LoadIcon';
export { default as EditIcon } from './new/EditIcon';
export { default as HomeIcon } from './new/HomeIcon';
export { default as DocumentIcon } from './new/DocumentIcon';
export { default as DeleteIcon } from './new/DeleteIcon';
export { default as ContentCopyIcon } from './new/ContentCopyIcon';
export { default as MoreIcon } from './new/MoreIcon';
export { default as SearchIcon } from './new/SearchIcon';
export { default as FilesIcon } from './new/FilesIcon';
export { default as PaymentMethodIcon } from './new/PaymentMethodIcon';
export { default as SocialIcon } from './new/SocialIcon';
// export { default as ArrowDownIcon } from './IconsList/ArrowDownIcon';
// export { default as CheckBoxIcon } from './IconsList/CheckBoxIcon';
// export { default as CloseIcon } from './IconsList/CloseIcon';
// export { default as EyeSlash } from './IconsList/EyeSlash';
// export { default as Minus } from './IconsList/Minus';
// export { default as Plus } from './IconsList/Plus';
// export { default as RadioBoxIcon } from './IconsList/RadioIcon';
// export { default as VerticalLine } from './IconsList/VerticalLine';

