import { createStyles } from '../Theme';
//import { ISliderExtended } from './index';

export default createStyles( (theme) => ({
  container: {
    fontFamily: theme.font,
    fontWeight: 600,
    fontSize: 12,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 100,
    position: 'relative',
    //padding: '0 15px',
    /*'& $thumb': {
      width: '100%',
      '&>div:not($inputContainerError)': {
        border: 'none',
        height: 'auto',
        padding: 0,
      },
      '&>div:focus-within:not($inputContainerError)': {
        border: 'none',
        outline: 'none',
      },
      '& $input': {
        '-webkit-appearance': 'none',
        '-webkit-tap-highlight-color': 'transparent',
        pointerEvents: 'none',
        position: 'absolute',
        zIndex: 5,
        height: 0,
        width: '100%',
        outline: 'none',
        cursor: 'pointer',
        padding: 0,
        margin: 0,
        '&::-webkit-slider-thumb': {
          '-webkit-appearance': 'none',
          '-webkit-tap-highlight-color': 'transparent',
          //backgroundColor: theme.primary.main,
          border: 'none',
          borderRadius: '50%',
          //boxShadow: '0 0 1px 1px #ced4da',
          //cursor: 'pointer',
          height: 30,
          width: 30,
          //marginTop: 6,
          //pointerEvents: 'all',
          //position: 'relative',
          background: 'transparent',
          color: 'transparent',
        },
        '&::-moz-range-thumb': {
          //backgroundColor: theme.primary.main,
          border: 'none',
          borderRadius: '50%',
          //boxShadow: '0 0 1px 1px #ced4da',
          //cursor: 'pointer',
          height: 30,
          width: 30,
          //marginTop: 6,
          //pointerEvents: 'all',
          //position: 'relative',
          background: 'transparent',
          color: 'transparent',
        },
      }
    },*/
  },
  thumb:  {

  },
  sliderThumbMin: (props: any) => ({
    backgroundColor: theme.primary.main,
    border: 'none',
    borderRadius: '50%',
    boxShadow: '0 0 1px 1px #ced4da',
    cursor: 'pointer',
    height: 30,
    width: 30,
    position: 'absolute',
    top: -12.5,
    zIndex: 5,
    //left: `${props.sliderThumbMin}%`,
    //pointerEvents: 'all',
    display: 'flex',
    justifyContent: 'center',
    /*left: 0,
    right: 0,*/
    //transform: 'translate(-50%, 0)',
  }),
  sliderThumbMax: (props: any) => ({
    backgroundColor: theme.primary.main,
    border: 'none',
    borderRadius: '50%',
    boxShadow: '0 0 1px 1px #ced4da',
    cursor: 'pointer',
    height: 30,
    width: 30,
    position: 'absolute',
    top: -12.5,
    zIndex: 5,
    //left: `${props.sliderThumbMax}%`
    display: 'flex',
    justifyContent: 'center',
    /*left: 0,
    right: 0,*/
    //transform: 'translate(-50%, 0)',
  }),
  thumbMinLabel: (props:any) => ({
    position: 'relative',
    bottom: 34,
    width: 'fit-content',
    color: theme.primary.contrast,
    fontSize: 12,
    height: 16,
    //left: props.minLeft,
    padding: '2px 4px',
    //margin: '0 auto',
    backgroundColor: theme.default.dark,
    borderRadius: 4,
    display: 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    //transform: 'translate(50%, 0)',
    '&$show': {
      display: 'block',
    }
  }),
  thumbMaxLabel: (props:any) => ({
    position: 'relative',
    bottom: 34,
    width: 'fit-content',
    color: theme.primary.contrast,
    fontSize: 12,
    height: 16,
    //left: props.maxLeft,
    padding: '2px 4px',
    //margin: '0 auto',
    backgroundColor: theme.default.dark,
    borderRadius: 4,
    display: 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    //transform: 'translate(-50%, 0)',
    '&$show': {
      display: 'block',
    }
  }),
  inputMinValue: (props:any) => ({
    position: 'relative',
    bottom: 38,
    zIndex: 5,
    margin: '0 auto',
    //left: props.minLeft,
    fontSize: 14,
    fontWeight: 600,
    color: theme.text.hint,
    width: 'fit-content',
    display: 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    //transform: 'translate(-50%, 0)',
    '&>div': {
      width: 'fit-content',
    },
    '&>div>div': {
      height: 32,
      //padding: '8px 5.5px',
      padding: 0,
      width: 'fit-content',
    },
    '& $input': {
      minWidth: 13,
      textAlign: 'center',
      padding: '8px 5.5px',
      lineHeight: 16,
      height: '-webkit-fill-available',
      border: 'none',
      '-moz-user-select': 'none',
      '-webkit-user-select': 'none',
      '-ms-user-select': 'none',
    },
    '&$show': {
      display: 'block',
    }
  }),
  inputMaxValue:(props:any) => ( {
    position: 'relative',
    bottom: 38,
    zIndex: 5,
    margin: '0 auto',
    right: 0,
    //left: props.maxLeft,
    fontSize: 14,
    fontWeight: 600,
    color: theme.text.hint,
    width: 'fit-content',
    display: 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    //transform: 'translate(-50%, 0)',
    '&>div': {
      width: 'fit-content',
    },
    '&>div>div': {
      height: 32,
      //padding: '8px 5.5px',
      padding: 0,
      width: 'fit-content',
    },
    '& $input': {
      minWidth: 13,
      textAlign: 'center',
      padding: '8px 5.5px',
      lineHeight: 16,
      height: '-webkit-fill-available',
      border: 'none',
      '-moz-user-select': 'none',
      '-webkit-user-select': 'none',
      '-ms-user-select': 'none',
    },
    '&$show': {
      display: 'block',
    }
  }),
  slider: {
    position: 'relative',
    width: '100%',
  },
  sliderTrack: {
    position: 'absolute',
    borderRadius: 3,
    height: 7,
    backgroundColor: theme.default.main,
    width: '100%',
    zIndex: 1,
  },
  sliderRange: {
    position: 'absolute',
    borderRadius: 3,
    height: 7,
    backgroundColor: theme.primary.main,
    opacity: 0.6,
    zIndex: 2,
  },
  sliderLeftValue: {
    position: 'absolute',
    color: theme.primary.contrast,
    fontSize: 12,
    right: 'calc(100% + 8px)',
    top: -6,
    padding: '2px 4px',
    backgroundColor: theme.default.dark,
    borderRadius: 4,
  },
  sliderRightValue: {
    position: 'absolute',
    color: theme.primary.contrast,
    fontSize: 12,
    left: 'calc(100% + 8px)',
    top: -6,
    padding: '2px 4px',
    backgroundColor: theme.default.dark,
    borderRadius: 4,
  },
  show: {
    '&$error>div>div:not(inputContainerError)': {
      borderColor: theme.error.main,
    },
    '&$error>div>div:focus-within:not(inputContainerError)': {
      borderColor: theme.error.main,
    },
  },
  error: {
    '&>div>div:not(inputContainerError)': {
      borderWidth: '1px',
      borderStyle: 'solid',
    }
  },
  dotsContainer: {
    position: 'absolute',
    width: '100%',
    height: '7px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 3
  },
  dot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.default.light,
  },
}))
