import { ISlider } from './index';
import { createStyles, toRem } from '../../components/Theme';


export default createStyles( (theme) => ({
  sliderRoot: {
    fontFamily: theme.font,
    fontWeight: 600,
    fontSize: toRem(12),
    height: toRem(30),
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    '&:not($disabled)': {
      '$thumb:hover': {
        zIndex: 6,
      },
      '& $thumbLabel$show': {
        display: 'flex',
      },
      '& $thumbInput$show': {
        display: 'block',
      }
    }
  },
  thumb: {
    backgroundColor: theme.colors.background.white,
    border: 'none',
    borderRadius: '50%',
    boxShadow: `0 0 ${toRem(4)} 0 #00000040`,
    cursor: 'pointer',
    height: toRem(30),
    width: toRem(30),
    position: 'absolute',
    top: toRem(-13),
    zIndex: 5,
    display: 'flex',
    justifyContent: 'center',
    touchAction: 'none',
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
  },
  disabled: {
    '& $thumb': {
      backgroundColor: theme.colors.neutralGray.light200,
    },
    '& $sideLabel, $sliderRange, $dotsContainer': {
      backgroundColor: theme.colors.neutralGray.medium300,
      color: '#E3E8EE',
    },
    '& $sliderTrack, $sliderRange, $thumb': {
      cursor: 'auto',
    }
  },
  thumbLabel: {
    position: 'relative',
    bottom: toRem(34),
    width: 'fit-content',
    color: theme.colors.contrast.white,
    fontSize: toRem(12),
    height: toRem(16),
    padding: `${toRem(2)} ${toRem(4)}`,
    backgroundColor: theme.colors.neutralGray.dark600,
    borderRadius: toRem(4),
    display: 'none',
    alignItems: 'center',
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
  },
  thumbInput: {
    position: 'relative',
    bottom: toRem(42),
    zIndex: 5,
    margin: '0 auto',
    fontSize: toRem(14),
    fontWeight: 600,
    color: theme.colors.text.tint,
    width: 'fit-content',
    display: 'none',
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
    '&>div': {
      width: 'fit-content',
    },
    '&>div>div': {
      height: toRem(34),
      padding: 0,
      width: 'fit-content',
    },
    '& $input': {
      minWidth: toRem(13),
      textAlign: 'center',
      padding: `${toRem(8)} ${toRem(5.5)}`,
      lineHeight: toRem(16),
      height: '-webkit-fill-available',
      borderRadius: toRem(4),
      border: 'none',
    },
  },
  slider: {
    position: 'relative',
    width: '100%',
    height: toRem(4),
  },
  sliderTrack: {
    position: 'absolute',
    borderRadius: toRem(3),
    height: toRem(4),
    backgroundColor: theme.colors.neutralGray.medium300,
    width: '100%',
    zIndex: 1,
    cursor: 'pointer',
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
  },
  sliderRange: (props: ISlider) => ({
    position: 'absolute',
    borderRadius: toRem(3),
    height: toRem(4),
    backgroundColor: theme.colors[props.color!].main500,
    opacity: 0.6,
    zIndex: 2,
    cursor: 'pointer',
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
  }),
  sideLabel: {
    color: theme.colors.contrast.white,
    fontSize: toRem(12),
    lineHeight: toRem(16),
    padding: `${toRem(2)} ${toRem(4)}`,
    margin: `0 ${toRem(8)}`,
    backgroundColor: theme.colors.neutralGray.main500,
    borderRadius: toRem(4),
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
  },
  sideIconLabel: {
    margin: `0 ${toRem(8)}`,
  },
  show: {
    '&$error>div>div:not(inputContainerError)': {
      borderColor: theme.colors.error.main500,
    },
    '&$error>div>div:focus-within:not(inputContainerError)': {
      borderColor: theme.colors.error.main500,
    },
  },
  error: {
    '&>div>div:not(inputContainerError)': {
      borderWidth: toRem(1),
      borderStyle: 'solid',
      borderColor: theme.colors.error.main500,
    }
  },
  dotsContainer: {
    position: 'absolute',
    width: '100%',
    height: toRem(4),
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 3,
  },
  dot: {
    width: toRem(4),
    height: toRem(4),
    borderRadius: toRem(2),
    backgroundColor: theme.colors.neutralGray.light100,
  },
}), { internalUsage: true })
