import { createStyles } from '../Theme';
import { ISlider } from './index';

export default createStyles( (theme) => ({
  sliderRoot: {
    fontFamily: theme.font,
    fontWeight: 600,
    fontSize: 12,
    height: 30,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    '&:not($disabled)': {
      '$thumb:hover': {
        zIndex: 6,
      },
      '& $thumbLabel$show': {
        display: 'flex',
      },
      '& $thumbInput$show': {
        display: 'block',
      }
    }
  },
  thumb: {
    backgroundColor: theme.background.default,
    border: 'none',
    borderRadius: '50%',
    boxShadow: '0 0 4px 0 #00000040',
    cursor: 'pointer',
    height: 30,
    width: 30,
    position: 'absolute',
    top: -13,
    zIndex: 5,
    display: 'flex',
    justifyContent: 'center',
    touchAction: 'none',
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
  },
  disabled: {
    '& $thumb': {
      backgroundColor: theme.default.light,
    },
    '& $sideLabel, $sliderRange, $dotsContainer': {
      backgroundColor: theme.default.main,
      color: '#E3E8EE',
    },
    '& $sliderTrack, $sliderRange, $thumb': {
      cursor: 'auto',
    }
  },
  thumbLabel: {
    position: 'relative',
    bottom: 34,
    width: 'fit-content',
    color: theme.primary.contrast,
    fontSize: 12,
    height: 16,
    padding: '2px 4px',
    backgroundColor: theme.default.dark,
    borderRadius: 4,
    display: 'none',
    alignItems: 'center',
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
  },
  thumbInput: {
    position: 'relative',
    bottom: 42,
    zIndex: 5,
    margin: '0 auto',
    fontSize: 14,
    fontWeight: 600,
    color: theme.text.hint,
    width: 'fit-content',
    display: 'none',
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
    '&>div': {
      width: 'fit-content',
    },
    '&>div>div': {
      height: 34,
      padding: 0,
      width: 'fit-content',
    },
    '& $input': {
      minWidth: 13,
      textAlign: 'center',
      padding: '8px 5.5px',
      lineHeight: '16px',
      height: '-webkit-fill-available',
      borderRadius: 4,
      border: 'none',
    },
  },
  slider: {
    position: 'relative',
    width: '100%',
    height: 4,
  },
  sliderTrack: {
    position: 'absolute',
    borderRadius: 3,
    height: 4,
    backgroundColor: theme.default.main,
    width: '100%',
    zIndex: 1,
    cursor: 'pointer',
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
  },
  sliderRange: (props: ISlider) => ({
    position: 'absolute',
    borderRadius: 3,
    height: 4,
    backgroundColor: theme[props.color!].main,
    opacity: 0.6,
    zIndex: 2,
    cursor: 'pointer',
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
  }),
  sideLabel: {
    color: theme.primary.contrast,
    fontSize: 12,
    lineHeight: '16px',
    padding: '2px 4px',
    margin: '0 8px',
    backgroundColor: theme.default.dark,
    borderRadius: 4,
    '-webkit-touch-callout': 'none',
    '-moz-user-select': 'none',
    '-webkit-user-select': 'none',
    '-ms-user-select': 'none',
    'user-select': 'none',
  },
  sideIconLabel: {
    margin: '0 8px',
  },
  show: {
    '&$error>div>div:not(inputContainerError)': {
      borderColor: theme.error.main,
    },
    '&$error>div>div:focus-within:not(inputContainerError)': {
      borderColor: theme.error.main,
    },
  },
  error: {
    '&>div>div:not(inputContainerError)': {
      borderWidth: '1px',
      borderStyle: 'solid',
      borderColor: theme.error.main,
    }
  },
  dotsContainer: {
    position: 'absolute',
    width: '100%',
    height: '4px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 3,
  },
  dot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: theme.default.light,
  },
}))
